export const HMI_VALUE_PROPERTY_NAMES = {
  0: { propertyName: "value", defaultValue: "50" },
  1: { propertyName: "minValue", defaultValue: "0" },
  2: { propertyName: "maxValue", defaultValue: "100" }, 
  3: { propertyName: "endLL", defaultValue: "15"},
  4: { propertyName: "endL", defaultValue: "30"},
  5: { propertyName: "startH", defaultValue: "70"},
  6: { propertyName: "startHH", defaultValue: "85"},
  7: { propertyName: "unitOfMeasure", defaultValue: "---" },
  8: { propertyName: "backgroundColor", defaultValue: "RGB(33,33,33)" },
  9: { propertyName: "degradedColor", defaultValue: "RGB(0,80,130)"},
  10: { propertyName: "textColor", defaultValue: "white" },
  11: { propertyName: "fontSizeValue", defaultValue: "13" },
  12: { propertyName: "fontSizeUnitOfMeasure", defaultValue: "7.5" },
  13: { propertyName: "fontSizeIndicatorNumber", defaultValue: "8" },
  14: { propertyName: "arrowWidth", defaultValue: "1.6"},
  15: { propertyName: "arrowColor", defaultValue: 'white'},
  16: { propertyName: "alarmBypass", defaultValue: "false"},
};